-- CreateEnum
CREATE TYPE "Role" AS ENUM ('ADMIN', 'PROVIDER', 'PATIENT');

-- CreateEnum
CREATE TYPE "UserStatus" AS ENUM ('PENDING', 'ACTIVE', 'INACTIVE');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "role" "Role" NOT NULL DEFAULT 'PATIENT',
ADD COLUMN     "status" "UserStatus" NOT NULL DEFAULT 'ACTIVE',
ALTER COLUMN "phone" DROP NOT NULL,
ALTER COLUMN "npiNumber" DROP NOT NULL,
ALTER COLUMN "credentials" DROP NOT NULL,
ALTER COLUMN "licenseNumber" DROP NOT NULL,
ALTER COLUMN "licenseExpirationDate" DROP NOT NULL,
ALTER COLUMN "licenseState" DROP NOT NULL,
ALTER COLUMN "homeStreetAddress" DROP NOT NULL,
ALTER COLUMN "homeCity" DROP NOT NULL,
ALTER COLUMN "homeState" DROP NOT NULL,
ALTER COLUMN "homeZipCode" DROP NOT NULL,
ALTER COLUMN "practiceAddress" DROP NOT NULL;
